### ISSUE TITLE
Contribution Weights

### ISSUE THREAD

**Issue by AmosHolland** [goudanough/WizARds#10]
The contribution weeks 1 and 2 for this fortnight are:

Alyssa - 0.96
Amin - 0.96
Amos - 0.96
Chengwei - 0.96
Nathaniel - 1.1
Rose - 1.1
Yiwen - 0.96

**Comment by rosefromthedead** [comment]
I agree

**Comment by a6-webm** [comment]
lgtm!

**Comment by Foxinatel** [comment]
# LGTM

**Comment by OwenBoisse** [comment]
I agree 👍

**Comment by LICHENGWEI-cloud** [comment]
i agree
