### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by rosefromthedead** [goudanough/WizARds#3]
We want (rollback?) networking with an authoritative server that decides on projectile collision, and some mechanism (prediction?) on the clients so they can render someone else's projectile.

**Comment by a6-webm** [comment]
> Note that there are a few rollback libraries out there on crates.io

https://crates.io/crates/bevy_ggrs
Yeah this actually seems like a really good idea, cause we'd end up not needing to make our own wire protocol.
